# Generated by Django 5.2.17 on 2026-09-25 07:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('devices', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(unique=True)),
                ('label', models.CharField(max_length=120)),
                ('field_type', models.CharField(choices=[('currency', 'Currency'), ('number', 'Number'), ('percentage', 'Percentage'), ('text', 'Text'), ('date', 'Date'), ('boolean', 'Boolean')], max_length=20)),
                ('is_required', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_calculated', models.BooleanField(default=False)),
                ('formula', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['sort_order', 'label'],
            },
        ),
        migrations.CreateModel(
            name='MonthlyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('month', models.PositiveSmallIntegerField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted')], default='draft', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reports', to='devices.deviceassignment')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reports', to='devices.device')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-year', '-month', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ReportValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decimal_value', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('text_value', models.TextField(blank=True)),
                ('date_value', models.DateField(blank=True, null=True)),
                ('bool_value', models.BooleanField(blank=True, null=True)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='values', to='reports.reportfield')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='reports.monthlyreport')),
            ],
        ),
        migrations.AddConstraint(
            model_name='monthlyreport',
            constraint=models.UniqueConstraint(fields=('device', 'year', 'month'), name='unique_device_month_report'),
        ),
        migrations.AddConstraint(
            model_name='monthlyreport',
            constraint=models.CheckConstraint(condition=models.Q(('month__gte', 1), ('month__lte', 12)), name='report_month_range'),
        ),
        migrations.AddConstraint(
            model_name='reportvalue',
            constraint=models.UniqueConstraint(fields=('report', 'field'), name='unique_report_field_value'),
        ),
    ]
