# Generated by Django 5.2.17 on 2026-09-25 09:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LedgerEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('cost', 'Cost'), ('income', 'Income')], max_length=10)),
                ('description', models.CharField(max_length=200)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=14)),
                ('unit', models.CharField(max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='reports.monthlyreport')),
            ],
            options={
                'ordering': ['kind', 'sort_order', 'id'],
            },
        ),
    ]
